function Hd = PPGBandpass
%UNTITLED Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.2 and the DSP System Toolbox 8.5.
% Generated on: 22-Nov-2014 03:10:36

% Chebyshev Type II Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 125;  % Sampling Frequency

Fstop1 = 0.5 ;         % First Stopband Frequency
Fpass1 = 1 ;         % First Passband Frequency
Fpass2 = 3.5 ;           % Second Passband Frequency
Fstop2 = 4 ;         % Second Stopband Frequency
Astop1 = 60;          % First Stopband Attenuation (dB)
Apass  = 1;           % Passband Ripple (dB)
Astop2 = 60;          % Second Stopband Attenuation (dB)
match  = 'passband';  % Band to match exactly

% Construct an FDESIGN object and call its CHEBY2 method.
h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, Astop2, Fs);
Hd = design(h, 'cheby2', 'MatchExactly', match);

% [EOF]
